site_name: Portfolio Site
site_url: https://haruzova.github.io/eob-pf/

theme: 

  favicon: assets/misc/donspin.gif
  logo: https://drive.google.com/thumbnail?id=1OaspU3pMMzDgaLhEGvdD4oiczAvKvFOv
  
  name: material

  font: false
  palette:
    - scheme: dark
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    - scheme: light
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - mkdocs-video
    - header.autohide

plugins:
  - search
  - mkdocs-video
  - ezlinks:
      wikilinks: true
      reference_links: true
  - glightbox
  

extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      line_spans: __span
  - tables
